source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXWeChatSDK_Example' do
  pod 'BXWeChatSDK', :path => '../'

  target 'BXWeChatSDK_Tests'do
    inherit! :search_paths
  end

end
